# Generated by Django 3.2.15 on 2022-10-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_rename_familiares_familiaresapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamiliaresApp',
            new_name='Familiar',
        ),
    ]
