# Generated by Django 3.2.15 on 2022-10-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0003_rename_familiaresapp_familiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_de_nacimiento',
        ),
    ]
