# Generated by Django 4.1.1 on 2022-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_remove_familiar_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='camadamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('camada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cursomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('camada', models.IntegerField()),
            ],
        ),
    ]
