# Generated by Django 4.1.1 on 2022-10-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0005_camadamodel_cursomodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Alumno',
        ),
    ]
