# Generated by Django 4.1.1 on 2022-10-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0006_rename_familiar_alumno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Estudiante',
        ),
    ]
