# Generated by Django 4.1.1 on 2022-10-11 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0009_remove_estudiante_camada_remove_estudiante_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='año',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='camada',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
