# Generated by Django 4.1.1 on 2022-10-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0010_estudiante_año_estudiante_camada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='año',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='camada',
            field=models.CharField(max_length=30),
        ),
    ]
