# Generated by Django 4.1.1 on 2022-10-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0011_remove_estudiante_año_alter_estudiante_camada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiantemodel',
        ),
    ]
